### ISSUE TITLE
Cannot resolve dependency on jgit 3.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by mlevin2** [shabanovd/eXgit#8]
When attempting to build via "mvn clean package" I get this error:

```
[ERROR] Failed to execute goal on project eXgit: Could not resolve dependencies for project org.exist-db:eXgit:jar:0.3.0: Could not find artifact org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0-SNAPSHOT in jgit-repository (http://download.eclipse.org/jgit/maven) -> [Help 1]
```

**Comment by mlevin2** [comment]
I was able to get past this error by specifying a newer jgit version in the pom.xml. However, I'm now getting this error, and no version of jgit that I've been able to locate so far seems to resolve it.

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/mlevin/eXgit/src/main/java/org/exist/git/xquery/Clone.java:[87,20] cannot find symbol
  symbol:   method setFS(org.eclipse.jgit.util.FS_eXistdb)
  location: class org.eclipse.jgit.api.CloneCommand
[INFO] 1 error
[INFO] -------------------------------------------------------------
```

**Comment by shabanovd** [comment]
you have to use this patched version https://github.com/eXist-db/jgit

**Comment by mlevin2** [comment]
Thanks. I had to skip tests building jgit, and I had to update the pom.xml on eXgit to specify that it should use source and target java 1.5, but once I did that, I was able to get the .xar to build. I'll give it a try to see if it works as expected.
