### ISSUE TITLE
@git:time in git:log needs to fix

### ISSUE THREAD

**Issue by wstarcev** [shabanovd/eXgit#9]
RevCommit.getCommitTime() have to be multiplied by 1000L

I have XQuery workaround of it:
datetime:timestamp-to-datetime(xs:long($commit/@git:time) * xs:long(1000))

this return true time. May be inclue it in Java code?

**Comment by shabanovd** [comment]
fixed by 1a23f4e815551e48e4d6c4994198e1f3ad9295ae
